### ISSUE TITLE
Compare IL between Bancor approach, simple Uniswap approach for single-asset LPs

### ISSUE THREAD

**Issue by poliwop** [galacticcouncil/HydraDX-simulations#16]

**Comment by RudolfGolubich** [comment]
I should be capable to provide a comparison based on analysing the different invariants to quantify the sensitivity to external price changes. Would this be of help?

**Comment by poliwop** [comment]
Yeah that sounds helpful, are you talking about simulation or an analytical comparison? From doing the math I think they are identical, this task was just to simulate them side-by-side to check it.
(They are identical, that is, if you drop the IL protection that Bancor incorporates.)

Note that #15 is thus a prereq, and I'm working on it now... though getting a notebook showing IL for the current implementation would be a start.

**Comment by RudolfGolubich** [comment]
If I am not restricted to a specific simulation environment and can easily implement Bancor in addition to Hydra, I could do a numeric and an analytic comparison in parallel, so that - hopefully - one valididates the other. The analytic approach would be finished faster, given, that Bancor has a "clean" invariant. It would result in two supply and parameter dependent formulas f({R},{ C}) that relate dV, the change of value, to dp, the change of external price in first order. A calculation in second order, that is, dp^2, would also be possible, but more elaborate. I am quite sure that first order is sufficient since AMS are active 24/7/365,25, hence are continously exposed to the wider market.

How fast would you need the results and what incentive is at the table?

**Comment by poliwop** [comment]
Ah sure... This is probably not an issue for you to look at tbh for what you want to do then, it's really a note to myself reminding me to do it once I'm done with the prereq (specifically in Python/cadCAD). Hence why there's not much of a description. Maybe I will use the "Help Wanted" label if I post items that we're looking for help with?
