### ISSUE TITLE
protocol fee not applied to resolved Q_purchased_asset AMM state

### ISSUE THREAD

**Issue by matttyb80** [galacticcouncil/HydraDX-simulations#37]
[Single Swap Verification](https://github.com/galacticcouncil/HydraDX-simulations/blob/mb_event_verification/hydradx_update/SingleSwap.ipynb)

Q-1 state (result of r2 purchase) does not account for the fee
![image](https://user-images.githubusercontent.com/33430774/152007590-76d564f8-2480-4aa5-bb3d-eaef21634a42.png)

**Comment by poliwop** [comment]
I do not believe this is a bug, I believe the test was not accounting for the Lerna that is minted to the asset j pool when the asset fee is added back to the pool.

I will copy the notebook and check in a version with a corrected test illustrating the correct math.

**Comment by poliwop** [comment]
@matttyb80 In b8096b60a7d00975f464398fb1ddd4f4fac71d23 I checked in a slightly modified version of your sheet, which I fixed with the correct hub token/Lerna accounting for the second pool. The Lerna fee is correctly decreasing how much Lerna gets traded into pool 2, and this is all being accounted for all the way through the asset being traded out of the pool.

Then, the asset fee is applied and the fee amount is added back to the pool, and _Lerna is minted to maintain the price_. This minting is where the extra Lerna was coming from, and it is correct. You will find that the amount you were seeing was not actually exactly the same as if the fee_HDX had been zero, but was very close since fee_HDX and fee_assets were identical and low.

Note that the test doesn't quite pass in my notebook either, but the values match to 9 decimals which probably indicates that it's correct... I usually use pytest.approx in the hypothesis tests due to this type of rounding error.

Let us know if this doesn't look correct to you, or if there's some inconsistency between this explanation and the specs.

**Comment by matttyb80** [comment]
I continued the verification test in the notebook to include the lerna. I did this concurrently, so I had just posted an update to the  above notebook [Single Swap + Lerna](https://github.com/galacticcouncil/HydraDX-simulations/blob/mb_event_verification/hydradx_update/SingleSwap.ipynb) without seeing this. 
There is still some difference in the Q-1 amount (6 tokens) between computed and expected. Will look to see if this is rounding or fee or order of resolution.

**Comment by poliwop** [comment]
I believe "new_Q_1" depends on the incorrectly calculated delta_qj so applying my fix from SingleSwap_Colin will probably fix it.

**Comment by poliwop** [comment]
@matttyb80 can this be closed?

**Comment by matttyb80** [comment]
yes, this is now resolved
